language: go
go:
  - "1.11.x"
jobs:
  include:
    - os: linux
      dist: trusty
      sudo: required
      services:
        - docker
      script:
        - make test
        - make testacc
        - make vet
        - make website-test
    - os: osx
      script:
        - make test
        - make testacc
    - os: windows
      script:
        # TODO: ensure windows setup can support binary testing
        - TF_ACC=1 go test -v ./...
env:
  - GO111MODULE=on GOFLAGS=-mod=vendor

install:
# This script is used by the Travis build to install a cookie for
# go.googlesource.com so rate limits are higher when using `go get` to fetch
# packages that live there.
# See: https://github.com/golang/go/issues/12933
- bash scripts/gogetcookie.sh

branches:
  only:
  - master
