sudo: false
language: go

go:
- "1.10.x"
- tip

os:
  - linux
  - osx

install:
- go get github.com/kardianos/govendor
- go get github.com/alecthomas/gometalinter
- gometalinter --install

script:
- make test
- make vendor-status
# this provider is local only, so it can run it's acc tests in travis
- make testacc

branches:
  only:
  - master
matrix:
  fast_finish: true
  allow_failures:
  - go: tip
